
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: app-container
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase

volumes:
  mongodb_data: